before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - GO386=softfloat
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: darwin
        goarch: 386
    main: .

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  name_template: "v{{.Version}}"
#  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^WIP:'
      - Merge pull request
      - Merge branch
      - go mod tidy


dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/zhilyaev/aws-sts-auth:{{ .Version }}"
      - "ghcr.io/zhilyaev/aws-sts-auth:latest"

    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

      - "--platform=linux/amd64"
      - "--target=goreleaser"
    goos: linux
    goarch: amd64
    use_buildx: true
